# Generated by Django 4.2.4 on 2023-09-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Adm',
        ),
        migrations.AlterField(
            model_name='comida',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
