# Generated by Django 4.2.4 on 2023-09-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_administrador_adm_alter_comida_preco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adm',
        ),
        migrations.DeleteModel(
            name='Garcon',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comida',
        ),
        migrations.AddField(
            model_name='pedido',
            name='comidas',
            field=models.ManyToManyField(to='core.comida'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='imagem',
            field=models.ImageField(upload_to='imagens/'),
        ),
    ]
