# Generated by Django 4.2.4 on 2023-10-20 20:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_adm_delete_garcon_remove_pedido_comida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comidas',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 17, 55, 40, 191606)),
        ),
        migrations.CreateModel(
            name='ComidasPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comida')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
    ]
