# Generated by Django 4.2.4 on 2023-10-20 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_comidas_remove_pedido_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 19, 45, 34, 712916)),
        ),
    ]
