# Generated by Django 4.2.4 on 2023-10-22 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 15, 29, 55, 696055)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
