# Generated by Django 4.2.4 on 2023-10-22 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pedido_data_alter_pedido_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 26, 40, 430522)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
