# Generated by Django 4.2.4 on 2023-10-22 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pedido_data_alter_pedido_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 22, 17, 27, 12, 250447)),
        ),
    ]
