# Generated by Django 4.2.4 on 2023-10-26 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 9, 23, 46, 223210)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.BooleanField(),
        ),
    ]
